### ISSUE TITLE
Compiling fails on Linux 

### ISSUE THREAD

**Issue by interstar** [micknoise/Maximilian#24]
Been a while since I looked at this. But trying to compile on Ubuntu 13.10 I get the following (from the command line).

OSS :

RtAudio.cpp:6391:23: fatal error: soundcard.h: No such file or directory
 #include "soundcard.h"

ALSA :
RtAudio.cpp:5148:28: fatal error: alsa/asoundlib.h: No such file or directory
 #include &lt;alsa/asoundlib.h&gt;

Jack : 
RtAudio.cpp:1798:23: fatal error: jack/jack.h: No such file or directory
 #include &lt;jack/jack.h&gt;

Are there files? Submodules missing? Or is there something I need to install / do before trying to compile?

**Comment by alasdairKyle** [comment]
how do u fix this issue been using your libery as part of my uni project

**Comment by diversen** [comment]
You need some dev libs: 

E.g.: 

RtAudio.cpp:5148:10: fatal error: alsa/asoundlib.h: No such file or directory
 5148 | #include <alsa/asoundlib.h>

This should be resolved with (I am on Ubuntu 19.10): 

`sudo aptitude install libasound2-dev`
