### ISSUE TITLE
Maximilian.h error  

### ISSUE THREAD

**Issue by loboere** [micknoise/Maximilian#65]
I'm using visual studio 2010
my operating system is windows 7

```
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(147): error C2864: 'maxiFractionalDelay::writePointer' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(148): error C2864: 'maxiFractionalDelay::readPointer' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(300): warning C4244: '=' : conversion from 'double' to 'short', possible loss of data
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(458): error C2864: 'maxiEnv::holdtime' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(514): warning C4244: 'argument' : conversion from 'double' to 'int', possible loss of data
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(539): warning C4244: 'argument' : conversion from 'double' to 'int', possible loss of data
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(540): warning C4244: 'argument' : conversion from 'double' to 'int', possible loss of data
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(666): error C2864: 'maxiKick::output' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(667): error C2864: 'maxiKick::outputD' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(669): error C2864: 'maxiKick::useDistortion' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(670): error C2864: 'maxiKick::useLimiter' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(671): error C2864: 'maxiKick::useFilter' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(672): error C2864: 'maxiKick::distortion' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(673): error C2864: 'maxiKick::inverse' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(676): error C2864: 'maxiKick::gain' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(691): error C2864: 'maxiSnare::output' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(692): error C2864: 'maxiSnare::outputD' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(694): error C2864: 'maxiSnare::useDistortion' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(695): error C2864: 'maxiSnare::useLimiter' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(696): error C2864: 'maxiSnare::useFilter' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(697): error C2864: 'maxiSnare::distortion' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(698): error C2864: 'maxiSnare::inverse' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(701): error C2864: 'maxiSnare::gain' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(721): error C2864: 'maxiHats::output' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(722): error C2864: 'maxiHats::outputD' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(724): error C2864: 'maxiHats::useDistortion' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(725): error C2864: 'maxiHats::useLimiter' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(726): error C2864: 'maxiHats::useFilter' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(727): error C2864: 'maxiHats::distortion' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(728): error C2864: 'maxiHats::inverse' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(731): error C2864: 'maxiHats::gain' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(774): error C2864: 'maxiSampler::originalPitch' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(776): error C2864: 'maxiSampler::outputD' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(780): error C2864: 'maxiSampler::useDistortion' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(781): error C2864: 'maxiSampler::useLimiter' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(782): error C2864: 'maxiSampler::useFilter' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(783): error C2864: 'maxiSampler::distortion' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(784): error C2864: 'maxiSampler::inverse' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(787): error C2864: 'maxiSampler::gain' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(789): error C2864: 'maxiSampler::currentVoice' : only static const integral data members can be initialized within a class
2>c:\users\damian\desktop\of_v0.7.4_vs2010_release\addons\ofxmaxim\libs\maximilian.h(799): error C2864: 'maxiSampler::sustain' : only static const integral data members can be initialized within a class
```

**Comment by micknoise** [comment]
I don't know if the current example project is optimised for VS2010 on windows 7. You should find that if you check out an earlier version of the repo from 2010, the windows example will run. Also, you're working in an older version of OF (0.74). I have no idea if a system this old is even supportable anymore.
